version: '2'
services:
  edr:
    build: .
    ports:
    - 81:80
    environment:
      NODE_ENV: production
      PORT: 80
    depends_on:
    - mongo
  mongo:
    image: mvertes/alpine-mongo
  edr-uploader:
    build: ../edr-uploader
    volumes:
    - ../edr-uploader/data:/data/
    depends_on:
    - mongo

  redis:
    image: 'redis'
    command: redis-server --appendonly yes
    expose:
      - '6379'
    volumes:
      - /data
